pub use monero_wallet as wallet;
pub mod wallet_rpc;

pub use ::monero_address::MoneroAddress as Address;
pub use ::monero_address::Network;
pub use ::monero_oxide_ext::{PrivateKey, PublicKey};
pub use curve25519_dalek::scalar::Scalar;
pub use swap_core::monero::primitives::*;
pub use wallet::{Daemon, Wallet, Wallets};

/// Derive the primary (legacy) address of a wallet from its raw
/// spend/view secret keys.
///
/// Equivalent to `wallet.main_address()` on an opened monero-sys wallet,
/// but needs no open wallet — useful when we want the address before (or
/// in parallel with) opening it through monero-sys.
pub fn primary_address_from_secrets(
    spend_secret_key: &[u8; 32],
    view_secret_key: &[u8; 32],
    network: Network,
) -> anyhow::Result<Address> {
    let spend = PublicKey::from_private_key(&PrivateKey::from_slice(spend_secret_key)?).decompress();
    let view = PublicKey::from_private_key(&PrivateKey::from_slice(view_secret_key)?).decompress();
    Ok(Address::new(network, monero_address::AddressType::Legacy, spend, view))
}

#[cfg(test)]
mod tests {
    //! Cross-checks `primary_address_from_secrets` against ground-truth
    //! addresses produced by `monero-wallet-rpc`. The fixtures live in
    //! the `monero-wallet2-adapter` crate and are generated by
    //! `monero-wallet2-adapter/tests/fixtures/regenerate.sh`.

    use super::*;

    fn hex32(h: &str) -> [u8; 32] {
        let mut out = [0u8; 32];
        hex::decode_to_slice(h, &mut out).expect("valid 32-byte hex");
        out
    }

    #[test]
    fn derives_primary_address_matching_wallet_rpc() {
        // Ground-truth addresses come from `monero-wallet-rpc`'s
        // `get_address` (see `monero-wallet2-adapter/tests/fixtures/*.json`).
        let fixture_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("monero-wallet2-adapter")
            .join("tests")
            .join("fixtures");

        let fixtures = ["wallet_empty", "wallet_short", "wallet_long"];
        let mut checked = 0;
        for name in fixtures {
            let path = fixture_dir.join(format!("{name}.json"));
            let Ok(body) = std::fs::read_to_string(&path) else {
                // Skip if fixtures aren't shipped with this checkout.
                continue;
            };
            let v: serde_json::Value = serde_json::from_str(&body).expect("fixture json");
            let spend = hex32(v["spend_secret_key"].as_str().unwrap());
            let view = hex32(v["view_secret_key"].as_str().unwrap());
            let expected = v["primary_address"].as_str().unwrap();

            let addr = primary_address_from_secrets(&spend, &view, Network::Mainnet)
                .expect("derivation");
            assert_eq!(
                addr.to_string(),
                expected,
                "{name}: derived address does not match wallet-rpc ground truth",
            );
            checked += 1;
        }

        assert!(checked > 0, "no fixtures found to check against");
    }
}
