use crate::signature::SignedMessage;
use bytes::Bytes;
use libp2p_identity::PeerId;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

pub mod client;
pub mod codec;
pub mod server;
pub mod signature;
pub mod storage;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct UnsignedPinnedMessage {
    /// This ID is essentially a nonce
    /// It is generated by the sender and we cannot guarantee that it is unique
    /// If we need a unique identifier, we should hash the entire message
    pub id: Uuid,
    pub sender: PeerId,
    pub receiver: PeerId,
    pub ttl: u64,
    pub priority: u64,
    pub encrypted_content: Bytes,
}

pub type SignedPinnedMessage = SignedMessage<UnsignedPinnedMessage>;

pub mod pin {
    use super::*;

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct Request {
        pub message: SignedPinnedMessage,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
    pub enum Response {
        Stored,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
    pub enum Error {
        ResourceLimitExceeded,
        MalformedMessage,
        Other,
    }
}

pub mod fetch {
    use super::*;

    #[derive(Debug, Clone, Serialize, Deserialize, Default)]
    pub struct Request;

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct Response {
        /// Hashes of all messages where: `hash.receiver == client.peer_id`
        pub incoming: Vec<signature::MessageHash>,
        /// Hashes of all messages where: `hash.sender == client.peer_id`
        pub outgoing: Vec<signature::MessageHash>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
    pub enum Error {
        StorageFailure,
        Other,
    }
}

pub mod pull {
    use super::*;

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct Request {
        /// Hashes of the message the client wants to download from the server
        pub hashes: Vec<signature::MessageHash>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct Response {
        pub messages: Vec<SignedPinnedMessage>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
    pub enum Error {
        StorageFailure,
        Other,
    }
}
