[package]
name = "eigensync"
version = "0.1.0"
edition = "2021"
description = "Simple distributed document synchronization using Automerge CRDTs and libp2p"
license = "MIT"
repository = "https://github.com/UnstoppableSwap/unstoppableswap-gui"

[[example]]
name = "device_sync"
path = "examples/device_sync.rs"

[dependencies]
# Core dependencies
serde = { workspace = true }
uuid = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }

# Automerge for CRDT functionality
automerge = "0.6"

# Networking with libp2p
libp2p = { workspace = true, features = ["request-response", "tcp", "noise", "yamux", "macros", "cbor", "tokio"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "time"] }
env_logger = "0.11"

[lints]
workspace = true
