[package]
name = "swap-orchestrator"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "orchestrator"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
bollard = "0.13.0" # old version because of dependency conflicts with testcontainers
chrono = "0.4.41"
clap = { version = "4.5.48", features = ["derive"] }
compose_spec = "0.3.0"
dialoguer = { workspace = true }
monero = { workspace = true }
serde_yaml = "0.9.34"
swap-env = { path = "../swap-env" }
tokio = { workspace = true, features = ["macros"] }
toml = { workspace = true }
url = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
vergen = { workspace = true }

[lints]
workspace = true
