name: "Set Monero Environment Variables"
description: "Sets common environment variables for Monero dependencies across workflows"
runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: bash
      run: |

        # GUI-specific Ubuntu dependencies
        echo "DEPS_GUI_UBUNTU_SPECIFIC=libgtk-3-dev libappindicator3-dev librsvg2-dev libwebkit2gtk-4.1-0 libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-0 libjavascriptcoregtk-4.1-dev gir1.2-javascriptcoregtk-4.1 gir1.2-webkit2-4.1" >> $GITHUB_ENV

        # Build tooling (Linux)
        echo "DEPS_BUILD_LINUX=autoconf nsis mingw-w64 build-essential pkg-config libtool ccache make cmake gcc g++ git curl lbzip2 gperf g++-mingw-w64-x86-64" >> $GITHUB_ENV

        # Build tooling (macos)
        echo "DEPS_BUILD_MACOS=autoconf automake pkg-config libtool ccache make cmake gcc git curl lbzip2 gperf" >> $GITHUB_ENV

        # APT configuration for better reliability
        echo 'APT_SET_CONF_COMMAND<<EOF
        sudo tee -a /etc/apt/apt.conf.d/80-custom << APTEOF
        Acquire::Retries "3";
        Acquire::http::Timeout "120";
        Acquire::ftp::Timeout "120";
        APTEOF
        EOF' >> $GITHUB_ENV

    - name: Crabnebula identifier
      shell: bash
      run: |
        echo "CN_APPLICATION=unstoppableswap/unstoppableswap-gui-rs" >> $GITHUB_ENV

    - name: Set platform identifiers
      shell: bash
      run: |
        # Platform identifiers used in various workflows
        echo "UBUNTU=ubuntu-24.04" >> $GITHUB_ENV
        echo "UBUNTU_PLATFORM_ID=ubuntu-24.04" >> $GITHUB_ENV
        echo "MACOS_INTEL=macos-13" >> $GITHUB_ENV
        echo "WINDOWS=windows-latest" >> $GITHUB_ENV
        echo "WINDOWS_PLATFORM_ID=windows-latest" >> $GITHUB_ENV
