[package]
name = "pgp-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
pgp = { workspace = true }
tracing = { workspace = true }
rand_chacha = { workspace = true }

[lints]
workspace = true
