/*
 * Intercambio.app API
 *
 * API endpoint for retrieving path information from Intercambio.app, including detailed state and trade information.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePathResponse {
    /// The UUID of the created path (present on success; otherwise, empty object).
    #[serde(rename = "path_uuid", skip_serializing_if = "Option::is_none")]
    pub path_uuid: Option<String>,
}

impl CreatePathResponse {
    pub fn new() -> CreatePathResponse {
        CreatePathResponse {
            path_uuid: None,
        }
    }
}

