/*
 * Intercambio.app API
 *
 * API endpoint for retrieving path information from Intercambio.app, including detailed state and trade information.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreatePathRequestIncludeServices : List of services to include (string or comma-separated string or array).
/// List of services to include (string or comma-separated string or array).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreatePathRequestIncludeServices {
    String(String),
    ArrayVecString(Vec<String>),
}

impl Default for CreatePathRequestIncludeServices {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

