/*
 * Intercambio.app API
 *
 * API endpoint for retrieving path information from Intercambio.app, including detailed state and trade information.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Currency {
    /// Network of the currency (e.g., Bitcoin, Ethereum).
    #[serde(rename = "network")]
    pub network: String,
    /// Symbol of the currency (e.g., BTC, ETH).
    #[serde(rename = "symbol")]
    pub symbol: String,
}

impl Currency {
    pub fn new(network: String, symbol: String) -> Currency {
        Currency {
            network,
            symbol,
        }
    }
}

