/*
 * Intercambio.app API
 *
 * API endpoint for retrieving path information from Intercambio.app, including detailed state and trade information.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PathResponseUrl {
    /// Clearnet URL for the trade path (e.g., https://intercambio.app/trade/{path_uuid}).
    #[serde(rename = "clearnet")]
    pub clearnet: String,
    /// Tor URL for the trade path (e.g., http://ybnc7t4gnaixrvawshppx6nauxrvyxf4nmppfk74ztqgd46q3ifjl4id.onion/trade/{path_uuid}).
    #[serde(rename = "tor")]
    pub tor: String,
}

impl PathResponseUrl {
    pub fn new(clearnet: String, tor: String) -> PathResponseUrl {
        PathResponseUrl {
            clearnet,
            tor,
        }
    }
}

