/*
 * Intercambio.app API
 *
 * API endpoint for retrieving path information from Intercambio.app, including detailed state and trade information.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PathResponseChat {
    /// Clearnet chat URL for support related to the path (e.g., https://orangefren.com/chat/new?context_site=eigenwallet&context_data={path_uuid}).
    #[serde(rename = "clearnet")]
    pub clearnet: String,
    /// Tor chat URL for support related to the path (e.g., https://orangefren.com/chat/new?context_site=eigenwallet.tor&context_data={path_uuid}).
    #[serde(rename = "tor")]
    pub tor: String,
}

impl PathResponseChat {
    pub fn new(clearnet: String, tor: String) -> PathResponseChat {
        PathResponseChat {
            clearnet,
            tor,
        }
    }
}

