/*
 * Intercambio.app API
 *
 * API endpoint for retrieving path information from Intercambio.app, including detailed state and trade information.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TradeProviderTrade {
    /// Response from the provider when the trade was created (likely a JSON string).
    #[serde(rename = "create_response")]
    pub create_response: String,
    /// ID of the trade on the provider.
    #[serde(rename = "id")]
    pub id: String,
    /// Current status of the trade on the provider.
    #[serde(rename = "status")]
    pub status: String,
}

impl TradeProviderTrade {
    pub fn new(create_response: String, id: String, status: String) -> TradeProviderTrade {
        TradeProviderTrade {
            create_response,
            id,
            status,
        }
    }
}

