name: "Create release"

on:
  pull_request:
    types:
      - closed

jobs:
  create_release:
    name: Create from merged release branch
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actionhippie/swap-space@v1
        with:
          size: 15G

      - name: Extract version from branch name
        id: extract-version
        shell: python
        run: |
          import os
          branch_name = "${{ github.event.pull_request.head.ref }}"
          version = branch_name.split("/")[1]

          with open(os.environ['GITHUB_OUTPUT'], 'a') as output_file:
              output_file.write(f'version={version}\n')

      - name: Extract changelog section for release
        id: changelog
        uses: coditory/changelog-parser@v1
        with:
          version: ${{ steps.extract-version.outputs.version }}

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOTTY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract-version.outputs.version }}
          release_name: ${{ steps.extract-version.outputs.version }}
          draft: false
          prerelease: false
          body: ${{ steps.changelog.outputs.description }}
          commitish: ${{ github.event.pull_request.merge_commit_sha }}
